### ISSUE TITLE
prosper_logging - rotating file handlers debug

### ISSUE THREAD

**Issue by lockefox** [EVEprosper/ProsperCommon#1]
logging issues when prosper_logging object runs for >24hrs.  Also issues on "virgin run" on new logfile that clear up on second run

**Comment by lockefox** [comment]
`log_freq` key probably needs to be set to `midnight`

http://stackoverflow.com/questions/35571237/why-python-logging-module-rotating-day-log-mess-up

**Comment by lockefox** [comment]
error from ProsperBot:

`  File "prosperbot.py", line 347, in <module>
    bot.run(BOT_TOKEN)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/client.py", line 485, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1312, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/client.py", line 273, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 833, in on_message
    yield from self.process_commands(message)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 822, in process_commands
    yield from command.invoke(ctx)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "prosperbot.py", line 279, in price
    company_name = get_company_name(symbol, cache_override_bool)
  File "prosperbot.py", line 195, in get_company_name
    cached_name = check_company_cache(ticker)
  File "prosperbot.py", line 169, in check_company_cache
    LOGGER.info('--company name found in cache: ' + company_name)
Message: '--company name found in cache: Twitter, Inc. Common Stock'
Arguments: ()
[INFO:prosperbot.py--check_company_cache:169] --company name found in cache: Twitter, Inc. Common Stock
Ignoring exception in command price
Traceback (most recent call last):
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "prosperbot.py", line 287, in price
    percent = float(percent.replace('%',''))
ValueError: could not convert string to float: 'N/A'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 822, in process_commands
    yield from command.invoke(ctx)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/core.py", line 367, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/prosper/ProsperUtilities/venv_bot/lib/python3.5/site-packages/discord/ext/commands/core.py", line 52, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: could not convert string to float: 'N/A'
`

**Comment by lockefox** [comment]
testing prosperbot.py on v0.3.0 with new logger framework

**Comment by lockefox** [comment]
Log creates correctly in the first pass, but then is missing after `midnight` when rolling filehandle should update

**Comment by lockefox** [comment]
added pytest for exercising `TimedRotatingFilehandler` 

#75c872261fd1a29299e759c6e700d210b24b8f74

**Comment by lockefox** [comment]
FIXED

configparser always returns `str()`.  `backupCount` requires `int()`

https://github.com/EVEprosper/ProsperCommon/commit/7ac00d7aac975970fc477bd83fcd9f809a30d005
