### ISSUE TITLE
Loggers cannot have blank configuration in ProsperApplication

### ISSUE THREAD

**Issue by lockefox** [EVEprosper/ProsperCommon#26]
```bash
`LOGGING.log_format` not found in global config
`LOGGING.discord_recipient` not found in global config
Traceback (most recent call last):
  File "/Users/jpurcell/venvs/.venv_vincent/bin/GetNews", line 11, in <module>
    load_entry_point('vincent-lexicon', 'console_scripts', 'GetNews')()
  File "/Users/jpurcell/source/vincent-lexicon/vincent_crons/GetNews.py", line 172, in run_main
    GetNewsCLI.run()
  File "/Users/jpurcell/venvs/.venv_vincent/lib/python3.6/site-packages/plumbum/cli/application.py", line 500, in run
    retcode = inst.main(*tailargs)
  File "/Users/jpurcell/source/vincent-lexicon/vincent_crons/GetNews.py", line 147, in main
    self.logger.info('hello world')
  File "/Users/jpurcell/venvs/.venv_vincent/lib/python3.6/site-packages/prosper/common/prosper_cli.py", line 83, in logger
    custom_args=id_string
  File "/Users/jpurcell/venvs/.venv_vincent/lib/python3.6/site-packages/prosper/common/prosper_logging.py", line 282, in configure_discord_logger
    discord_obj.webhook(discord_webhook)
  File "/Users/jpurcell/venvs/.venv_vincent/lib/python3.6/site-packages/prosper/common/prosper_logging.py", line 484, in webhook
    raise Exception('Invalid url format, looking for: ' + self.__webhook_url_format)
Exception: Invalid url format, looking for: https://discordapp.com/api/webhooks/(\d+)/([\w-]+)
```
Need to be able to run without notifications if not supplied

**Comment by lockefox** [comment]
May require adding logic to understand that `{{jinja.template}}` counts as blank
